[package]
name = "canvas"
version = "0.1.0"
authors = ["shivshank"]

[features]
default = []

drawing = ["gl", "cgmath"]

[dependencies]
cgmath = { version = "0.15.0", optional = true }
gl = { version = "0.6.0", optional = true }
